At 11 03 07 08
AlexTom22/TestCapitalCom pull request #357
Opened 2023-07-24 18:26 UTC by AndrSam1

Добавил 8-й тест, добавил новый локатор для горизонтального баннера, исправление ошбки в match-case ( в том числе и прошлых ТС)

2023-07-24 18:27 UTC, AndrSam1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT_11.03.07_08 | Educations > Menu item [What is a margin?] > Test button [Try Free Demo] in Block "Want a test drive?"](https://trello.com/c/rgELjzVq/189-at11030708-educations-menu-item-what-is-a-margin-test-button-try-free-demo-in-block-want-a-test-drive)

2023-07-24 19:19 UTC, AlexTom22 commented on tests/US_11_Education/US_11-02-06_Indices_trading/us_11-02-06_indices_trading_test.py
> +            case ("NoReg" | "Reg/NoAuth"):
по-моему, круглые скобки не нужны. Но и ошибку вызвать не должны

2023-07-24 19:27 UTC, AlexTom22 commented on tests/US_11_Education/US_11-03-07_What_is_a_margin/US_11-03-07_What_is_a_margin_test.py
> +                test_element.assert_login(d, link)
Не обновил себе ветку с гитхаба, когда я писал в чате.
В результате затираешь своей старой версией этой строеи мои утренние исправления test_element.assert_login(d, cur_language, link).
Возьми за практику, перед тем как пушить, обязательно спулить актуальный код и если надо, разрешать конфликт локально, а не на гитхабе, что наверное придется делать мне.
Из-за этого местаи еще дальше, уже вижу, вынужден пока отказать в одобрении и слиянии

2023-07-24 19:31 UTC, AlexTom22 commented on tests/US_11_Education/US_11-03-07_What_is_a_margin/US_11-03-07_What_is_a_margin_test.py
> +                test_element.assert_login(d, link)
и здесь затираешь мои важные изменения. Я же предупреждал, что подправил не только общий метод класса но и ваши вызовы, т.е. в ваших скриптах.
Пока отказываю. Обнови свою локальную ветку до удаленной мастер. Слей их локально и после этого заново запушь свои обновления

2023-07-24 19:34 UTC, AndrSam1 commented on tests/US_11_Education/US_11-03-07_What_is_a_margin/US_11-03-07_What_is_a_margin_test.py
> +                test_element.assert_login(d, link)
обновил, твои строчки столкнулись с моими, конфликт решал на своей стороне, перезалил

2023-07-24 19:35 UTC, AlexTom22 requested changes
Сделай так, как я тебе написал выше:
1. В локальную мастер ветку сделай git pull origin master
2. Перейди на рабочую локальную ветку
3. git merge master
4. при необходимости устрани конфлик в пользу гитхаба
5. git push origin AndrSam1
6. обнови PR

2023-07-25 07:27 UTC, AndrSam1 commented
> 

Ровно так, как ты написал я и делал изначально при первом коммте, но в 3-х местах теста what-is-margin я принял при решении конфликта свои строки, тк убирал там закомментированные строки, Обрати внимание, в последнем коммите я добавил в эти 3 места cur_language, сейчас все так, как ты просишь

2023-07-25 07:39 UTC, AlexTom22 approved these changes

2023-07-25 07:39 UTC, merged