modified test 8
AlexTom22/TestCapitalCom pull request #428
Opened 2023-08-19 14:15 UTC by podchasova11

US_11-03-03_Trend_Trading_test
 add new test_8

2023-08-19 17:45 UTC, AlexTom22 commented on tests/US_11_Education/US_11-03-03_Trend_Trading/US_11-03-03_Trend_Trading_test.py
> +                test_element.assert_signup(d, cur_language, link)
здесь, согласно ЧЛ ожидается открытие формы регистрации на трейдинговой платформе. Используемый тобой метод проверяет на странице capital.com. Замени метод

2023-08-19 17:46 UTC, AlexTom22 commented on tests/US_11_Education/US_11-03-03_Trend_Trading/US_11-03-03_Trend_Trading_test.py
> +                test_element.assert_login(d, cur_language, link)
здесь, согласно ЧЛ ожидается открытие формы авторизации на трейдинговой платформе. Используемый тобой метод проверяет на странице capital.com. Замени метод

2023-08-19 17:49 UTC, AlexTom22 requested changes
уточни языки, на которых работает этот ТК и отбрази это на уровне ТК, а не на уровне проверки наличия пунктов меню по локаторам.
ТК будет легче читаться

2023-08-20 09:28 UTC, podchasova11 commented on tests/US_11_Education/US_11-03-03_Trend_Trading/US_11-03-03_Trend_Trading_test.py
> +                test_element.assert_signup(d, cur_language, link)
test_element = AssertClass(d, link)
        match cur_role:
            case "NoReg":
                test_element.assert_signup_form_on_the_trading_platform(d)
                #  test_element.assert_signup(d, cur_language, link)
            case "Reg/NoAuth":
                test_element.assert_login_form_on_the_trading_platform(d)
                #  test_element.assert_login(d, cur_language, link)
            case "Auth":
                test_element.assert_trading_platform_v2(d, link)

2023-08-20 09:34 UTC, podchasova11 commented
> уточни языки, на которых работает этот ТК и отбрази это на уровне ТК, а не на уровне проверки наличия пунктов меню по локаторам. ТК будет легче читаться

        build_dynamic_arg_v2(self, d, worker_id, cur_language, cur_country, cur_role, prob_run_tc,
                             "11.03.03", "Educations > Menu item [Trend Trading]",
                             "08", "Testing button [Explore Web Platform] in Block \"Sign up and trade smart today!\"")

        if cur_language != "":
            pytest.skip("This test-case only for english language")

        page_conditions = Conditions(d, "")

2023-08-20 11:23 UTC, AlexTom22 approved these changes
все ок

2023-08-20 11:23 UTC, merged