Add test-03(Button sell) & test_04(button buy). Please, review and merge
AlexTom22/TestCapitalCom pull request #473
Opened 2023-09-01 21:32 UTC by kornet82

2023-09-02 06:00 UTC, AlexTom22 commented
Task linked: [CU-8692j9fdt AT_11.02.02.01_03 | Education > Menu Item [Shares trading] > pages "Shares trading guide" selected in the list of Items > Test button [Sell] on Banner [Trading Instrument]](https://app.clickup.com/t/8692j9fdt)

2023-09-02 06:02 UTC, AlexTom22 commented
Task linked: [CU-8692j9fdw AT_11.02.02.01_04 | Education > Menu Item [Shares trading] > pages "Shares trading guide" selected in the list of Items > Test button [Buy] on the Banner [Trading Instrument]](https://app.clickup.com/t/8692j9fdw)

2023-09-02 06:07 UTC, AlexTom22 commented on pages/Education/shares_trading_locators.py
> +@Time    : 2023/05/24 13:55
это разве актуальная дата?

2023-09-02 06:14 UTC, AlexTom22 commented on pyproject.toml
> +python = "^3.11.0"
чем тебя не устраивает строка python = "^3.10"???
Зачем ты постоянно меняешь?
и вообще, в этот файл ты пока лезть не должен!
из за этого, а не одобрю твой PR
Верни все обратно

2023-09-02 06:15 UTC, AlexTom22 requested changes
верни как было в файле pyproject.toml и обнови свою ветку на гитхабе

2023-09-02 11:59 UTC, AlexTom22 commented
Паша, ты перед тем как пушить, забыл обновить свою локальную ветку актуальным кодом из мастер на гитхабе. Дело в том, что пока у тебя локально происходили изменения (достатоно и 5-10 минут), кто-то мог запушить, я я мог апрувить и слить его изменения в общую мастер ветку, создав расхождения, а может и конфликт с твоими создаваемыми наработками. Что получилось и в данный момент. Теперь конфликт по твоим коммитоам должен разрешать я, а так быть не должно. 
Их должен разрешать та, как автор своего кода.
Поэтому, сейчас я отказываю. Я даже не проверял код, потому что мне написало, что аж 5 твоих файлов имеют конфликт с мастер веткой.
Сделай так, как надо делать (ф написал в начале) перед пушем
И повтори пуш заново

2023-09-02 20:49 UTC, kornet82 commented on pages/Education/shares_trading_locators.py
> +@Time    : 2023/05/24 13:55
Исправил

2023-09-02 20:50 UTC, kornet82 commented on pyproject.toml
> +python = "^3.11.0"
Когда поэтри настраивал в первый раз, только с 3.11 работал. Сейчас почему-то работает и с 3.10. Исправил.

2023-09-03 04:17 UTC, AlexTom22 approved these changes

2023-09-03 04:17 UTC, merged