US_11-03-01 added test of button [Trade] in Most traded block
AlexTom22/TestCapitalCom pull request #696
Opened 2023-11-22 12:54 UTC by podchasova11

US_11-03-01_trading_strategies_guide_test:

- added test_11.03.01_03 of button [Trade] in Most traded block

2023-11-22 12:55 UTC, podchasova11 commented
Task linked: [CU-8692utzpc Py/AT_11.03.01_03 | Educations > Menu item [Trading Strategies Guide] >Test button [Trade] in Widget [Most traded]](https://app.clickup.com/t/8692utzpc)

2023-11-22 15:57 UTC, AlexTom22 commented on tests/US_11_Education/US_11-03-01_trading_strategies_guide/US_11-03-01_trading_strategies_guide_test.py
> +        cur_item_link = build_dynamic_arg_v3(self, d, worker_id, cur_language, cur_country, cur_role,
ты используешь версию 3 функции build_dynamic_arg, а с изменениями не ознакомилась, а именно, с форматом передаваемых параметров. Форма номера ТК не такой, как был во второй версии функции. Разберись

2023-11-22 15:58 UTC, AlexTom22 commented on tests/US_11_Education/US_11-03-01_trading_strategies_guide/US_11-03-01_trading_strategies_guide_test.py
> +        if cur_language not in ["", "de", "es", "it"]:
не все языки

2023-11-22 16:02 UTC, AlexTom22 requested changes
устрани замечания, указанные и в соответствующей карточке AT и здесь.

2023-11-23 14:39 UTC, AlexTom22 commented
Не дождавшись обновления твоей ветки с учетом замечаний, я закрываю твой PR

2023-11-23 14:39 UTC, closed without merging